### ISSUE TITLE
Work with Custom URL as Directory

### ISSUE THREAD

**Issue by aljawaid** [aljawaid/PluginManager#11]
**Normal routine:**
Kanboard shows its list of plugins in the directory
- show count
- show list
- show disabled url (non-link format)

**Define custom url for a different directory (testing, updated with new properties) a duplicate of `plugins.json`**
- do not show the official pugins, pull the list from the custom url
- add note that json files only for custom url

**Comment by aljawaid** [comment]
@creecros I just changed the plugin API url and no plugin available.... do you have any input on this?

I always thought if you just move the json to another location (which i did)... organisations can edit the json to have a specific list of plugins available.... so by changing the json api in the config fil the direct would show but it never.

Could you confirm that is by design?  I just cant see the point of being able to define a plugin api url if it dont show in kanboard

**Comment by aljawaid** [comment]
set to custom plugins json file in different location

![image](https://user-images.githubusercontent.com/10233708/202713769-7ae69a99-d1ec-4d48-9350-2422cabc4f1e.png)

**Comment by creecros** [comment]
you did something wrong

![image](https://user-images.githubusercontent.com/26339368/202717476-b80ae3d0-e97d-49ab-aa81-c3e15e502972.png)

**Comment by aljawaid** [comment]
ok your example prompted me to find an issue in my code, I will fix it tonight.

Tell me your screen size... that 'connectors' label is way off

**Comment by creecros** [comment]
1920 x 1080?

**Comment by aljawaid** [comment]
> 1920 x 1080?
> 
> ![image](https://user-images.githubusercontent.com/26339368/202722297-16ef1a10-87ca-4af1-8c59-269830d7fb86.png)

na, I cant reproduce it... must be fixed in the latest css file
