### ISSUE TITLE
Add New Plugin Properties to All Plugins in The Plugins Directory

### ISSUE THREAD

**Issue by aljawaid** [aljawaid/PluginManager#12]
Must sift through all plugins and add the new json properties
---
- [x] Add `last_updated` date to each plugin
- [x] Add `has_hooks` to my own plugins
- [x] Add `has_overrides` to my own plugins
- [x] Sort all plugins alphabetically in json file
- [x] Add properties to plugins 5+ years (oldest)
- [x] Add properties to plugins <4 weeks (recent)
- [x] Add properties to plugins <2 years
- [x] Add properties to plugins <3 years
- [x] Add properties to plugins <4 years
- [x] Add properties to plugins <5 years
- [ ] #21

**Comment by aljawaid** [comment]
[586e896220165bb993fd9c6921dea98e8bd7690f](https://github.com/kanboard/website/pull/365/commits/586e896220165bb993fd9c6921dea98e8bd7690f)

**Comment by aljawaid** [comment]
Updated my plugins [ae22985a4b92662c5409cef84545ee9797a6c491](https://github.com/kanboard/website/pull/369/commits/ae22985a4b92662c5409cef84545ee9797a6c491)

**Comment by aljawaid** [comment]
Update Other Developer Plugins

- Update with new properties
- Selected plugins updated within the last 4 weeks
https://github.com/kanboard/website/pull/369/commits/2dfae3f90af54eeb5989375b7c2ac4ce2a1c6972

**Comment by aljawaid** [comment]
All plugins in the json file have now been cleaned up!  Waiting for the last part to merge, then it will make sense in the Plugin Manager... nearly ready for first release

**Comment by aljawaid** [comment]
> feel like you are missing something with `has_overrides` as you have equated it to templates only.
> 
> whereas, models can also be overridden. example: https://github.com/creecros/userimport_wgroups

oh great at least somebody is monitoring my work haha.... 

`has_overrides` - i went through each plugin and i looked for overriding templates
`has_hooks` - any hooks attached or `on`... basically anything `hook`
`has_schema` - looked for a schema folder

I went through every single `plugin.php` of every 107 plugin.... nothing suggested a model was overriden and I didnt know it could be either.  Is it a big thing? unless you correct me, overriding models will not break kanboard as it just plays with the existing database data?

**Comment by creecros** [comment]
let's evaluate the differences.

If you override a template, why is it bad, or why would anyone care? Insert your answer here
Now, if you override a model, why would it be any different than above concerns? 

Templates display things to user. Models handle getting and saving the data. 

Let's make a real world comparison. A fuel gauge displays how much fuel you have. A fuel pump gets the fuel and sends it to the motor. Fuel Gauge = Template, Fuel Pump = Model. If the Template in this scenario breaks, you may run out of gas. If the fuel pump breaks, well shit, you can't even fill up the tank to get going again. Which is more bad?

**Comment by aljawaid** [comment]
> let's evaluate the differences.
> 
> If you override a template, why is it bad, or why would anyone care? Insert your answer here Now, if you override a model, why would it be any different than above concerns?
> 
> Templates display things to user. Models handle getting and saving the data.
> 
> Let's make a real world comparison. A fuel gauge displays how much fuel you have. A fuel pump gets the fuel and sends it to the motor. Fuel Gauge = Template, Fuel Pump = Model. If the Template in this scenario breaks, you may run out of gas. If the fuel pump breaks, well shit, you can't even fill up the tank to get going again. Which is more bad?

oh I see your point.... should I do a `has_models` too then? as `has_overrides` is done now (also, models are specific to database data and not templates) and also it can be clearer for the user if a plugin was just messing with models... if you have tried this plugin so far, as the directory is being merged by Frederic, a lot of information is coming out which changes the way we see plugins I reckon... I hope its useful to everybody.

Moving forward...
- should I do a `has_models`
- or should we change the perspective of `has_overrides` to include models?
- or shall we use `has_schema` to include plugins which use models?
- or leave it as it is for now (maybe nobody will even use the plugin other than me)

**Comment by creecros** [comment]
I would still say, `has_models` is quite different from overriding existing models. now the argument would be why not have `has_templates`

**Comment by aljawaid** [comment]
the initial idea of these properties was to provide a hint to the end user. `has_overrides` for example was supposed to be a prompt to "focus on that plugin if you have an issue"

I will leave it all as it is, already spent 6hrs on the plugin directory and considering more than half are over a few years old and not updated, I dont see the point in the extra effort.  If the plugin gets popular then we can review again.

**Comment by creecros** [comment]
ya, i never really was thinking, you should add something, `has_overrides` seems like the only property you would need, but if you are only accounting for overridden templates, then I feel like you are missing all possible overrides. All I was saying. Definitely would not Add a property, the one you have is definitive enough.

I only even noticed because I saw https://github.com/creecros/userimport_wgroups was marked as not having overrides, and I knew that to not be the case.

**Comment by aljawaid** [comment]
So we will use `has_overrides` and I will include models later but.... To detect the models, is it a case of if the model is in the `plugin.php` file then its a model override?

**Comment by creecros** [comment]
ya, thats a tough one, when you see something like this:
`$this->container['taskModificationModel'] = $this->container->factory(function ($c) {
            return new NewTaskModificationModel($c);
        });`

and in this case `taskModificationModel` is an existing model.

and here:
`        $this->container['taskValidator'] = $this->container->factory(function ($c) {
            return new NewTaskValidator($c);
        });
`
this is overridding the taskValidator, which exists within KB.
