### ISSUE TITLE
Show Type of Plugin

### ISSUE THREAD

**Issue by aljawaid** [aljawaid/PluginManager#13]
Show somehow whether the plugin is a plugin or an action plugin

**Comment by aljawaid** [comment]
> some are both

oh damn, so the `true` `false` wont work then? or can we use `true` `false` `both` in the json property?

**Comment by aljawaid** [comment]
> > some are both
> 
> oh damn, so the `true` `false` wont work then? or can we use `true` `false` `both` in the json property?

I requested to change to string type https://github.com/kanboard/website/pull/366

**Comment by creecros** [comment]
boolean is true or false, nothing else.
my point was that it doesn't really apply. actions are plugins, and plugins can be actions. it's a dicey question.

**Comment by aljawaid** [comment]
This is now merged yipee!

so in the future, we can use this as:
`yes` - action plugin
`no` - normal plugin
`both` - normal + action
`theme` - theme only plugin

**Comment by aljawaid** [comment]
_From the Kaboard Website README - https://github.com/kanboard/website/pull/369/commits/00c3055aa329d340c3ac1a480c670c39fe238d12_
- `is_type`
  - `plugin` or `action` or `theme` or `multi` or `connector`
  - Specify whether your plugin is:
    | Value | Type | Description |
    | ----- | ---- | ----------- |
    | `plugin` | Normal | _A plugin with no automatic actions_ |
    | `action` | Action | _A plugin for actions only_ |
    | `theme` | Normal | _A plugin for theming and styling of the interface_ |
    | `connector` | Normal | _A plugin connecting to third party services - may contain actions_ |
    | `multi` | Normal | _A plugin containing all or any combination of the above functions_ |
  - _String type_
