### ISSUE TITLE
Show 'Other' Icon on Plugin Info Page if >0

### ISSUE THREAD

**Issue by aljawaid** [aljawaid/PluginManager#22]
Based on this commit https://github.com/aljawaid/PluginManager/commit/abe9a9f0f7b9318a66e26abd784816ac11301294 which is for the Plugin Directory Page.

The same icon should only show if there is greater than 0 (soon there should always be zero as all plugins will be part of a type)

I think the `use Kanboard\Core\Plugin\Directory;` is correct in the controller and also the `'available_plugins' => Directory::getInstance($this->container)->getAvailablePlugins(); ?>`

but something is wrong in this:
```
<?php $totalOthers = isset($countTypes) ? ((count($available_plugins)) - (array_sum($countTypes)) ) : '0' ?>
        <?php if ($totalOthers > 0): ?>
<?php endif ?>
```

as the icon doesn't show, when it should currently (there are 86 others for now)

**Comment by creecros** [comment]
im so confused. what do you want?

![image](https://user-images.githubusercontent.com/26339368/202592390-55936000-bbe6-41e0-80ab-eef3cbe1543a.png)

**Comment by aljawaid** [comment]
> im so confused. what do you want?
> 
> ![image](https://user-images.githubusercontent.com/26339368/202592390-55936000-bbe6-41e0-80ab-eef3cbe1543a.png)

the pic is for the directory page... that works fine (tell me your screen size as the connector field needs resizing)

my problem, or what i want is on the `info/plugin-info.php` page which is where i have pushed the code but it needs fixing as it is not showing the icon... but it should as the count so far is 86 (like in your pic)

**Comment by creecros** [comment]
oh, well that's easy. 

take a look again at that template, and ask yourself this question. What is $count Types?

https://github.com/aljawaid/PluginManager/blob/1957c905fd5d4572d1c9dc9aa124bb0402fe93d9/Template/info/plugin-info.php#L105

did you define it?

**Comment by aljawaid** [comment]
thanks for that, it made sense and also it worked
