### ISSUE TITLE
Work Out Last Installed Date

### ISSUE THREAD

**Issue by aljawaid** [aljawaid/PluginManager#24]
There seems to be no date or information on when any plugin was installed.

Solution:
Scan the `/plugins` folder and the 'last modified' date of the individual plugin folder would be the date it was created (plugin was installed).

I found the `scan()` but tried using it but got absolutely nowhere.  Not much proper information on finding php date modified for directory, everybody talking about files.

Your thoughts? Or if it is easy, can you please create the function etc and tell me how to call it in the template?  

for installed plugins, if the date could be worked out, i'd like to fit it in each plugin installed table, probably under the 'up to date' status
![image](https://user-images.githubusercontent.com/10233708/202906385-7fd12f59-4fcc-4301-b555-8ef2092a1926.png)

**Comment by aljawaid** [comment]
@creecros @alfredbuehler Is it worth looking into this?

**Comment by creecros** [comment]
I dont know.

`filemtime();` on the directory will work tho

**Comment by aljawaid** [comment]
> I dont know.
> 
> `filemtime();` on the directory will work tho

any rough example of how the installed plugin folder would be called for each plugin? or is it just `filemtime($plugins);`

**Comment by creecros** [comment]
no. 

https://www.php.net/manual/en/function.filemtime.php

you have to do it on each plugin directory.

**Comment by aljawaid** [comment]
Cool

**Comment by aljawaid** [comment]
@creecros So I managed to get it done with the `installed plugins` page.

Just trying to figure out the same for the `directory` page for the plugins which are installed

**Comment by aljawaid** [comment]
Done for installed plugins, cant figure it out for available plugins (matching to installed versions) so will close this as it was more important to show in the installed page which is done.
