### ISSUE TITLE
Missing in the Kanboard Plugin Directory

### ISSUE THREAD

**Issue by Jeager2** [aljawaid/PluginManager#26]
The Plugin Manager does not exist in my Kanboard Plugin Directory
Application version: v1.2.25
PHP version: 8.1.12 

Lists: [Oxygen] and then [Project activity modifier]

**Comment by aljawaid** [comment]
Been waiting since 9 days....
https://github.com/kanboard/website/pull/376

**Comment by aljawaid** [comment]
done
