### ISSUE TITLE
Some glitches in displaying things

### ISSUE THREAD

**Issue by JustFxDev** [aljawaid/PluginManager#29]
Env:
  Latest Kanboard
  All PlugIns latest Version
  No Theme installed
  Latest Firefox Browser

Hi aljawaid,

there are a few visual glitches in the plugin-manager. Minor issues:

### Buttons in Installed PlugIn Section
Buttons for PlugIn Infos and the "Uninstall" and "Info" Buttons are not aligned, not same height. 
![grafik](https://user-images.githubusercontent.com/82320201/209464642-1eade4d6-b8cd-4b48-99e0-c6a953c370bb.png)

Depending on the width of the bowser window the info button are in one line but not all are the same height
![grafik](https://user-images.githubusercontent.com/82320201/209465053-112085f5-5b96-4f20-ac80-0dedea9694ae.png)

### Buttons Top of PlugIn Directory
When i press one of the buttons (PlugIn Type) nothing happens but the search field blinks one time. Is this meant to be a filter? Or is this by design?

![grafik](https://user-images.githubusercontent.com/82320201/209464789-7c00c4e0-71e2-4131-882d-43635d7f0231.png)

### PlugIn Info Page
The boxes are not aligned
![grafik](https://user-images.githubusercontent.com/82320201/209464988-2e9a247b-c93e-4b2a-94ab-656c3abfe166.png)

As written earlier in this post: minor issues.

Cheers, Fx

**Comment by aljawaid** [comment]
@JustFxDev Great I will work on these in the next few days... keep adding to this issue if you see any more UI glitches.

Please tell me your browser/screen size as I tried my best for desktops and laptops

**Comment by aljawaid** [comment]
> When i press one of the buttons (PlugIn Type) nothing happens but the search field blinks one time. Is this meant to be a filter? Or is this by design?

@JustFxDev this is by design

**Comment by aljawaid** [comment]
> The boxes are not aligned

@JustFxDev they **are** aligned, to include the extra icon on the left... should I change it to align the boxes only instead? I didnt do it that way originally as I thought the icon would look bad sticking out... also taking into account that most users would be on desktops and not smaller devices.

**Comment by aljawaid** [comment]
> ### Buttons in Installed PlugIn Section
> Buttons for PlugIn Infos and the "Uninstall" and "Info" Buttons are not aligned, not same height. ![grafik](https://user-images.githubusercontent.com/82320201/209464642-1eade4d6-b8cd-4b48-99e0-c6a953c370bb.png)
> Depending on the width of the bowser window the info button are in one line but not all are the same height ![grafik](https://user-images.githubusercontent.com/82320201/209465053-112085f5-5b96-4f20-ac80-0dedea9694ae.png)

@JustFxDev Hello, you should be getting this:

![image](https://user-images.githubusercontent.com/10233708/209781322-7de4fa62-288e-40f0-87fa-330d45a993ea.png)

What's your screen size?

**Comment by aljawaid** [comment]
@JustFxDev Try the latest changes

**Comment by JustFxDev** [comment]
Hi aljawaid,

downloaded and testet latest code. Result see next post.

**Comment by JustFxDev** [comment]
![Animation](https://user-images.githubusercontent.com/82320201/210075393-07abe4ae-8ebb-4335-b822-26c904e88e04.gif)

**Comment by JustFxDev** [comment]
![grafik](https://user-images.githubusercontent.com/82320201/210075518-d5ab1e32-4149-4028-82c1-2ec00c36c1d8.png)

**Comment by JustFxDev** [comment]
Sorry, forgotten: i'am on a 32" desktop. Sizing the browser window as needed.

**Comment by JustFxDev** [comment]
![grafik](https://user-images.githubusercontent.com/82320201/210075999-f212b4bc-fe0a-4e24-ac1f-217377d7ebf6.png)

**Comment by JustFxDev** [comment]
And again: minor issues. Cosmetics ;-)

**Comment by aljawaid** [comment]
> ![Animation](https://user-images.githubusercontent.com/82320201/210075393-07abe4ae-8ebb-4335-b822-26c904e88e04.gif) [ ![Animation](https://user-images.githubusercontent.com/82320201/210075393-07abe4ae-8ebb-4335-b822-26c904e88e04.gif) ](https://user-images.githubusercontent.com/82320201/210075393-07abe4ae-8ebb-4335-b822-26c904e88e04.gif) [ ](https://user-images.githubusercontent.com/82320201/210075393-07abe4ae-8ebb-4335-b822-26c904e88e04.gif)

kanboard itself is not mobile responsive so it is too much work for me to account for every screen size.  however, I will have a look at it and see if I can make any adjustments

**Comment by aljawaid** [comment]
> ![grafik](https://user-images.githubusercontent.com/82320201/210075999-f212b4bc-fe0a-4e24-ac1f-217377d7ebf6.png)

it is by design, taking into account the extra icon.... I can see its annoying you and to be honest, it does look a little out of place.... I will change it
