### ISSUE TITLE
CSS not selective enough - conflicts with other views

### ISSUE THREAD

**Issue by JustFxDev** [aljawaid/PluginManager#31]
Hi aljawaid,

i'am sorry for bothering again. But i've an other issue with ccs coming from the plugin-manager plugin and interfering with other views / pages in Kanboard.

This one overwrites css for my links (a elements) on the board. 

```
a, details, summary, i, img, table, tr, .btn-uninstall, svg, #PluginSideBar > ul li, figure {
    transition: var(--transition-pm);
}

a:hover {
    color: var(--pp-red-alt-2) !important;        <--- important is very bad for a plugin...
}
```

Here in this picture you can see that settings belonging to the plugin are active on my board view:

![grafik](https://user-images.githubusercontent.com/82320201/210103031-9ff8d03c-abe9-493a-9c83-68d4844fb05c.png)

I fear this is a general issue. Plugin CSS overwriting other, general settings, because it's not selective enough. The CSS should be dedicated to the plugin by using specific classes in the html and only mark out this classes or IDs.

Sorry, i'am not complaining! I appreciate your great contributions to Kanboard! But i think this can lead to seroius issues.

Cheers, Fx

**Comment by aljawaid** [comment]
the reason why you see a few global tags is because I copied the code from my KanboardCSS plugin.  I honestly didnt think any of my plugins would be popular or so interesting for others.

I will change it here and in my other plugins over the coming days.

**Comment by JustFxDev** [comment]
> honestly didnt think any of my plugins would be popular or so interesting for others.

😄 😄 👍
