### ISSUE TITLE
Pressing Enter on Filter Input Redirects Page to Dashboard

### ISSUE THREAD

**Issue by aljawaid** [aljawaid/PluginManager#33]
> Something I noticed in PluginManager just now. If I am on the “Plugin Directory” view, and enter some text in the filter textbox, the plugins are filtered accordingly. Good. But, if I press the “Enter” key at any time, I am teleported to my kanboard’s home page, the Dashboard view.

> I kind of reflexively hit the enter key, even when it’s not necessary, because it’s a normal “submit” action for a textbox/filter. So, I end up constantly bouncing between Plugin Directory and Dashboard when I’m trying to filter the list. Not a huge problem and not a common occurrence, but figured I’d share.

**Forum Post by @axb21:**
https://kanboard.discourse.group/t/new-plugin-pluginmanager/2492/24?u=aljawaid

**Comment by aljawaid** [comment]
@axb21 This is not a bug as forms are designed like this by standard. A workaround will be needed for each specific form.

**Comment by creecros** [comment]
@aljawaid 

don't use a form.

**Comment by creecros** [comment]
oh nm you got it, didnt see the commit
