### ISSUE TITLE
Issue with ThemeRevision

### ISSUE THREAD

**Issue by HumanG33k** [aljawaid/PluginManager#34]
Issue White text on white background.

https://github.com/greyaz/ThemeRevision

![Capture d’écran_2023-03-09_17-17-43](https://user-images.githubusercontent.com/1794193/224091338-fa3a316f-5707-4695-bbbf-2408ed69ea1f.png)

![Capture d’écran_2023-03-09_17-32-43](https://user-images.githubusercontent.com/1794193/224091330-030ef75d-9e8f-43e0-932d-494fb3751911.png)

cross issue https://github.com/greyaz/ThemeRevision/issues/20

**Comment by aljawaid** [comment]
![image](https://user-images.githubusercontent.com/10233708/224093340-64a05714-d4c3-476a-a09a-594e57551763.png)


Hello, this is how it should look.... I think the issue is with ThemeRevision possibly

**Comment by aljawaid** [comment]
Reviewing my code, the css code is already present, which you can easily override:

https://github.com/aljawaid/PluginManager/blob/a595d38b4918d6df59a7a3c70247b8f96e0d816c/Assets/css/plugin-manager.css#L472

https://github.com/greyaz/ThemeRevision/issues/20

**Comment by aljawaid** [comment]
I have sifted through all the code and found other unrelated conflicts which I have fixed... For the problem related to this issue, it is now down to @greyaz to resolve in his plugin
