### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Call to undefined function Kanboard\Plugin\PluginManager\Helper\curl_ini (PHP 8.1)

### ISSUE THREAD

**Issue by Skyridr** [aljawaid/PluginManager#45]
Using the latest Kanboard version 1.2.28 with PHP 8.1. When trying to access plugin directory, the screen is mostly white

![image](https://user-images.githubusercontent.com/6794064/232229008-5c91f742-c44f-4f02-bcc3-151e571a1a5f.png)

And this pops up in the logs:

> 2023/04/15 13:58:16 [error] 179399#179399: *185 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function Kanboard\Plugin\PluginManager\Helper\curl_init() in /var/www/xxx/plugins/PluginManager/Helper/PluginManagerHelper.php:60
> Stack trace:
>  /var/www/xxx/plugins/PluginManager/Template/plugin/directory.php(174): Kanboard\Plugin\PluginManager\Helper\PluginManagerHelper->lastUpdatedDirectory()
>  /var/www/xxxx/app/Core/Template.php(83): include('...')
>  /var/www/xxx/app/Helper/LayoutHelper.php(207): Kanboard\Core\Template->render()
>  /var/www/xxx/app/Helper/LayoutHelper.php(142): Kanboard\Helper\LayoutHelper->subLayout()
>  /var/www/xxx/app/Controller/PluginController.php(47): Kanboard\Helper\LayoutHelper->plugin()
>  /var/www/xxx/app/Core/Controller/Runner.php(77): Kanboard\Controller\PluginController->directory()
>  /var/www/xxx/app/Core/Controller/Runner.php(31): Kanboard\Core\Controller\Runner->executeController()
>  /var/w" while reading response header from upstream, client: xxx, server: xxx, request: "GET /extensions/directory HTTP/1.0", upstream: "fastcgi://unix:/run/php/php8.1-fpm.sock:", host: "xxx"

Any idea what it might be?

**Comment by aljawaid** [comment]
Do you have `curl` installed?

https://github.com/aljawaid/PluginManager/blob/master/Helper/PluginManagerHelper.php#L60

**Comment by aljawaid** [comment]
If you use https://github.com/aljawaid/KanboardSupport it should tell you or go to `About` page

![image](https://user-images.githubusercontent.com/10233708/232230788-87087fea-709c-4d4e-8dda-6807ef31ea88.png)


![image](https://user-images.githubusercontent.com/10233708/232230737-9d22887b-2d1e-4410-91f1-c9fb831a3cdf.png)

**Comment by Skyridr** [comment]
👍Thanks! You were indeed correct. I've installed KanBoardSupport as well, appreciate the quick reply.
