### ISSUE TITLE
Dynamic filtering of the plugin directory list on plugin types

### ISSUE THREAD

**Issue by alfredbuehler** [aljawaid/PluginManager#53]
In the plugin directory list, make the count section clickable, to filter on the appropriate plugin type.

![image](https://github.com/aljawaid/PluginManager/assets/2079289/ef5da888-e1cd-49be-8aa3-d93c7d73b8a6)

See also discussion https://github.com/aljawaid/PluginManager/discussions/52

**Comment by aljawaid** [comment]
This is excellent, thanks for this
