### ISSUE TITLE
Plugin name and button links for "AddSpendTime" wrong

### ISSUE THREAD

**Issue by QuantumQuacken** [aljawaid/PluginManager#64]
Plugin under Manual Plugins - [Repo link](https://github.com/Tagirijus/AddSpentTime/)
The name of the plugin is actually "AddSpen**t**Time", not "AddSpen**d**Time"
The readme and repo links indicated contain the same error in the URL, therefore GitHub returns a 404.

**Comment by aljawaid** [comment]
Hello, this is not actually an issues of the plugin, but the directory file which is updated and then gets pulled by PluginManager, even though Manual Plugins are exclusively displayed in PM.

I originally listed this to help @Tagirijus out so I will fix the errors your mentioned no issues.  

@Tagirijus I will update the manual plugin listing - you need to update the readme as it also contains the spelling typo. Or add me to the repo and I will do it.  You should transform your plugins for general release now to showcase your hardwork. Manual Plugins do not bring the same confidence for users as general plugins, and not everybody uses PluginManager.

**Comment by aljawaid** [comment]
@Tagirijus do you want me to switch your manual plugins to general plugins?

**Comment by aljawaid** [comment]
@QuantumQuacken Fixes will show in PM, once the pull request is merged here: https://github.com/kanboard/website/pull/458

**Comment by QuantumQuacken** [comment]
Hello! Thank you for explaining and sorry for disturbing you with unnecessary issues!
